# art_courses = ['Design', 'Art', [ [ ], 'English', 'Sketching' ]]

# art_courses[2][0].append('Communication')
# art_courses[2][0].clear()

# print(art_courses)
marks = [[ ],[],[ ],[ ]]

# Write down the output generated by the print function before and after the following operations.
print(len(marks)) # here output

marks[0].insert(0, 95)
marks[0].insert(0, 98)
marks[0].insert(0, 94)
marks[1].insert(0,97)
marks[1].insert(0,96)
marks[1].insert(0,99)
marks[2].insert(0,94)
marks[2].insert(0,91)
marks[2].insert(0,98)
marks[3].insert(0,91)
marks[3].insert(0,100)
marks[3].insert(0,95)

print(marks) # here
print(len(marks)) # here output
